name: example
description: Example project for the Automated Testing Framework.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  automated_testing_framework_example: ^1.0.3
  websafe_platform: ^1.0.5

dependency_overrides:
  automated_testing_framework:
    path: ../
  # automated_testing_framework_example:
  #   path: ../../automated_testing_framework_example

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets-src/icon.png"

flutter_native_splash:
  image: assets-src/splash.png
  color: "212121"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets-src/MaterialIcons-Regular.ttf
