name: example
description: Example project for the Automated Testing Framework.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework_example: ^2.0.0
  flutter:
    sdk: flutter

dependency_overrides:
  automated_testing_framework:
    path: ../
  # automated_testing_framework_example:
  #   path: ../../automated_testing_framework_example
  # automated_testing_framework_models:
  #   path: ../../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets-src/icon.png"

flutter_native_splash:
  image: assets-src/splash.png
  color: "212121"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets-src/MaterialIcons-Regular.ttf
