name: automated_testing_framework
description: A testing framework that allows in app tests to be built and executed in an automated way.
version: 3.0.5
homepage: https://github.com/peiffer-innovations/automated_testing_framework

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework_models: ^2.0.2
  child_builder: ^2.0.0
  convert: ^3.0.0
  device_info: ^2.0.0
  flutter:
    sdk: flutter
  form_validation: ^2.0.0
  intl: ^0.17.0
  json_class: ^2.0.0
  json_theme: ^2.0.0+1
  logging: ^1.0.1
  meta: ^1.3.0
  package_info: ^2.0.0
  provider: ^5.0.0
  static_translations: ^2.0.0
  uuid: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

flutter:
  uses-material-design: true
